"$schema" = 'https://starship.rs/config-schema.json'

format = """
 $directory($git_branch )($git_state )($rust )($deno )($nodejs )($python )$character
"""

right_format = """
$cmd_duration
"""

add_newline = false

[character]
format = "$symbol "
success_symbol = "[❯](bold #0ce830)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold #0ce830)"

[cmd_duration]
min_time = 5000
format = "[󰔟 $duration]($style)"

[directory]
style = "bold #00ccff"
read_only = " 󰌾"
read_only_style = "bold red"
truncation_symbol = ".../"
home_symbol = "~"
truncation_length = 3

[git_branch]
symbol = ""
format = "[$symbol( $branch(:$remote_branch))]($style)"

[git_state]
format = "[$progress_current/$progress_total]($style)"

[deno]
format = "[$symbol ($version)]($style)"
symbol = ""

[nodejs]
format = "[$symbol ($version)]($style)"
symbol = ""

[python]
symbol = ""
format = "[$symbol ($version)( ${pyenv_prefix})( $virtualenv)]($style)"

[rust]
symbol = ""
format = "[$symbol ($version)]($style)"

[line_break]
disabled = true
