"$schema" = 'https://starship.rs/config-schema.json'

format = """
 $directory( $git_branch $git_status)$character
"""

right_format = """
$cmd_duration
"""

add_newline = false

[character]
format = "$symbol "
success_symbol = "[❯](bold #0ce830)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold #0ce830)"

[cmd_duration]
min_time = 5000
format = "[ﮫ $duration]($style)"

[directory]
style = "bold #00ccff"
read_only = " "
read_only_style = "bold red"
truncation_symbol = "../"
home_symbol = "~"
truncation_length = 3

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[line_break]
disabled = true
