#!/bin/bash

# Auto start

sxhkd &
pgrep bspswallow || bspswallow &
$HOME/.config/wm-scripts/autostart.sh &
$HOME/.config/bspwm/polybar.sh &

# Monitor

bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
# bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
# bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
# bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9

# BSPWM config

bspc config border_radius                 5
bspc config border_width                  2
bspc config window_gap                    8
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config click_to_focus                any
bspc config focus_follows_pointer         true
bspc config split_ratio                   0.50
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

# BSPWM colors

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#88c0d0"
bspc config focused_border_color "#b48ead"

# BSPWM rules
bspc rule -a Screenkey manage=off
bspc rule -a Gimp state=floating follow=on
